apiVersion: v1
kind: Pod
metadata:
  name: docksec-pod
  labels: 
    app: docksec-pod
spec:
  containers:
    - name: docksec
      image: docksec6/docksec:v1
      ports:
        - containerPort: 8080
