#!/bin/bash
apt-get update
apt-get upgrade -y
apt install --only-upgrade apt  # 
apt install --only-upgrade bash  # 
apt install --only-upgrade binutils  # 
apt install --only-upgrade binutils-common  # 
apt install --only-upgrade binutils-x86-64-linux-gnu  # 
apt install --only-upgrade bsdutils  # 
apt install --only-upgrade bzip2  # 
apt install --only-upgrade comerr-dev  # 
apt install --only-upgrade coreutils  # 
apt install --only-upgrade cpp-8  # 
apt install --only-upgrade curl  # 
apt install --only-upgrade debian-archive-keyring  # 
apt install --only-upgrade dirmngr  # 
apt install --only-upgrade dpkg  # 
apt install --only-upgrade dpkg-dev  # 
apt install --only-upgrade e2fsprogs  # 
apt install --only-upgrade fdisk  # 
apt install --only-upgrade g++-8  # 
apt install --only-upgrade gcc-8  # 
apt install --only-upgrade gcc-8-base  # 
apt install --only-upgrade gir1.2-rsvg-2.0  # 
apt install --only-upgrade git  # 
apt install --only-upgrade git-man  # 
apt install --only-upgrade gnupg  # 
apt install --only-upgrade gnupg-l10n  # 
apt install --only-upgrade gnupg-utils  # 
apt install --only-upgrade gpg  # 
apt install --only-upgrade gpg-agent  # 
apt install --only-upgrade gpgconf  # 
apt install --only-upgrade gpgsm  # 
apt install --only-upgrade gpgv  # 
apt install --only-upgrade gpg-wks-client  # 
apt install --only-upgrade gpg-wks-server  # 
apt install --only-upgrade gzip  # 
apt install --only-upgrade http-cache-semantics  # 
apt install --only-upgrade icu-devtools  # 
apt install --only-upgrade imagemagick  # 
apt install --only-upgrade imagemagick-6-common  # 
apt install --only-upgrade imagemagick-6.q16  # 
apt install --only-upgrade iproute2  # 
apt install --only-upgrade json-schema  # 
apt install --only-upgrade krb5-multidev  # 
apt install --only-upgrade libaprutil1  # 
apt install --only-upgrade libapt-pkg5.0  # 
apt install --only-upgrade libasan5  # 
apt install --only-upgrade libatomic1  # 
apt install --only-upgrade libbinutils  # 
apt install --only-upgrade libblkid1  # 
apt install --only-upgrade libblkid-dev  # 
apt install --only-upgrade libbz2-1.0  # 
apt install --only-upgrade libbz2-dev  # 
apt install --only-upgrade libc6  # 
apt install --only-upgrade libc6-dev  # 
apt install --only-upgrade libcairo2  # 
apt install --only-upgrade libcairo2-dev  # 
apt install --only-upgrade libcairo-gobject2  # 
apt install --only-upgrade libcairo-script-interpreter2  # 
apt install --only-upgrade libc-bin  # 
apt install --only-upgrade libcc1-0  # 
apt install --only-upgrade libc-dev-bin  # 
apt install --only-upgrade libcom-err2  # 
apt install --only-upgrade libcroco3  # 
apt install --only-upgrade libcurl3-gnutls  # 
apt install --only-upgrade libcurl4  # 
apt install --only-upgrade libcurl4-openssl-dev  # 
apt install --only-upgrade libdb5.3  # 
apt install --only-upgrade libdb5.3-dev  # 
apt install --only-upgrade libde265-0  # 
apt install --only-upgrade libdjvulibre21  # 
apt install --only-upgrade libdjvulibre-dev  # 
apt install --only-upgrade libdjvulibre-text  # 
apt install --only-upgrade libdpkg-perl  # 
apt install --only-upgrade libelf1  # 
apt install --only-upgrade libexpat1  # 
apt install --only-upgrade libexpat1-dev  # 
apt install --only-upgrade libext2fs2  # 
apt install --only-upgrade libfdisk1  # 
apt install --only-upgrade libfreetype6  # 
apt install --only-upgrade libfreetype6-dev  # 
apt install --only-upgrade libfribidi0  # 
apt install --only-upgrade libgcc1  # 
apt install --only-upgrade libgcc-8-dev  # 
apt install --only-upgrade libgcrypt20  # 
apt install --only-upgrade libglib2.0-0  # 
apt install --only-upgrade libglib2.0-bin  # 
apt install --only-upgrade libglib2.0-data  # 
apt install --only-upgrade libglib2.0-dev  # 
apt install --only-upgrade libglib2.0-dev-bin  # 
apt install --only-upgrade libgmp10  # 
apt install --only-upgrade libgmp-dev  # 
apt install --only-upgrade libgmpxx4ldbl  # 
apt install --only-upgrade libgnutls28-dev  # 
apt install --only-upgrade libgnutls30  # 
apt install --only-upgrade libgnutls-dane0  # 
apt install --only-upgrade libgnutls-openssl27  # 
apt install --only-upgrade libgnutlsxx28  # 
apt install --only-upgrade libgomp1  # 
apt install --only-upgrade libgssapi-krb5-2  # 
apt install --only-upgrade libgssrpc4  # 
apt install --only-upgrade libharfbuzz0b  # 
apt install --only-upgrade libheif1  # 
apt install --only-upgrade libhogweed4  # 
apt install --only-upgrade libicu63  # 
apt install --only-upgrade libicu-dev  # 
apt install --only-upgrade libidn2-0  # 
apt install --only-upgrade libidn2-dev  # 
apt install --only-upgrade libitm1  # 
apt install --only-upgrade libjbig0  # 
apt install --only-upgrade libjbig-dev  # 
apt install --only-upgrade libjpeg62-turbo  # 
apt install --only-upgrade libjpeg62-turbo-dev  # 
apt install --only-upgrade libjpeg-dev  # 
apt install --only-upgrade libk5crypto3  # 
apt install --only-upgrade libkadm5clnt-mit11  # 
apt install --only-upgrade libkadm5srv-mit11  # 
apt install --only-upgrade libkdb5-9  # 
apt install --only-upgrade libkrb5-3  # 
apt install --only-upgrade libkrb5-dev  # 
apt install --only-upgrade libkrb5support0  # 
apt install --only-upgrade libksba8  # 
apt install --only-upgrade libldap-2.4-2  # 
apt install --only-upgrade libldap-common  # 
apt install --only-upgrade liblsan0  # 
apt install --only-upgrade liblz4-1  # 
apt install --only-upgrade liblzma5  # 
apt install --only-upgrade liblzma-dev  # 
apt install --only-upgrade libmagickcore-6-arch-config  # 
apt install --only-upgrade libmagickcore-6-headers  # 
apt install --only-upgrade libmagickcore-6.q16-6  # 
apt install --only-upgrade libmagickcore-6.q16-6-extra  # 
apt install --only-upgrade libmagickcore-6.q16-dev  # 
apt install --only-upgrade libmagickcore-dev  # 
apt install --only-upgrade libmagickwand-6-headers  # 
apt install --only-upgrade libmagickwand-6.q16-6  # 
apt install --only-upgrade libmagickwand-6.q16-dev  # 
apt install --only-upgrade libmagickwand-dev  # 
apt install --only-upgrade libmariadb3  # 
apt install --only-upgrade libmariadb-dev  # 
apt install --only-upgrade libmariadb-dev-compat  # 
apt install --only-upgrade libmount1  # 
apt install --only-upgrade libmount-dev  # 
apt install --only-upgrade libmpx2  # 
apt install --only-upgrade libncurses5-dev  # 
apt install --only-upgrade libncurses6  # 
apt install --only-upgrade libncurses-dev  # 
apt install --only-upgrade libncursesw5-dev  # 
apt install --only-upgrade libncursesw6  # 
apt install --only-upgrade libnettle6  # 
apt install --only-upgrade libnghttp2-14  # 
apt install --only-upgrade libopenexr23  # 
apt install --only-upgrade libopenexr-dev  # 
apt install --only-upgrade libopenjp2-7  # 
apt install --only-upgrade libopenjp2-7-dev  # 
apt install --only-upgrade libpcre16-3  # 
apt install --only-upgrade libpcre2-8-0  # 
apt install --only-upgrade libpcre3  # 
apt install --only-upgrade libpcre32-3  # 
apt install --only-upgrade libpcre3-dev  # 
apt install --only-upgrade libpcrecpp0v5  # 
apt install --only-upgrade libperl5.28  # 
apt install --only-upgrade libpixman-1-0  # 
apt install --only-upgrade libpixman-1-dev  # 
apt install --only-upgrade libpng16-16  # 
apt install --only-upgrade libpng-dev  # 
apt install --only-upgrade libpq5  # 
apt install --only-upgrade libpq-dev  # 
apt install --only-upgrade libprocps7  # 
apt install --only-upgrade libpython2.7-minimal  # 
apt install --only-upgrade libpython2.7-stdlib  # 
apt install --only-upgrade libpython2-stdlib  # 
apt install --only-upgrade libpython3.7-minimal  # 
apt install --only-upgrade libpython3.7-stdlib  # 
apt install --only-upgrade libpython-stdlib  # 
apt install --only-upgrade libquadmath0  # 
apt install --only-upgrade librsvg2-2  # 
apt install --only-upgrade librsvg2-common  # 
apt install --only-upgrade librsvg2-dev  # 
apt install --only-upgrade libsasl2-2  # 
apt install --only-upgrade libsasl2-modules-db  # 
apt install --only-upgrade libseccomp2  # 
apt install --only-upgrade libsepol1  # 
apt install --only-upgrade libsepol1-dev  # 
apt install --only-upgrade libsmartcols1  # 
apt install --only-upgrade libsqlite3-0  # 
apt install --only-upgrade libsqlite3-dev  # 
apt install --only-upgrade libss2  # 
apt install --only-upgrade libssh2-1  # 
apt install --only-upgrade libssl1.1  # 
apt install --only-upgrade libssl-dev  # 
apt install --only-upgrade libstdc++6  # 
apt install --only-upgrade libstdc++-8-dev  # 
apt install --only-upgrade libsvn1  # 
apt install --only-upgrade libsystemd0  # 
apt install --only-upgrade libtasn1-6  # 
apt install --only-upgrade libtasn1-6-dev  # 
apt install --only-upgrade libtiff5  # 
apt install --only-upgrade libtiff-dev  # 
apt install --only-upgrade libtiffxx5  # 
apt install --only-upgrade libtinfo6  # 
apt install --only-upgrade libtsan0  # 
apt install --only-upgrade libubsan1  # 
apt install --only-upgrade libudev1  # 
apt install --only-upgrade libunbound8  # 
apt install --only-upgrade libuuid1  # 
apt install --only-upgrade libwebp6  # 
apt install --only-upgrade libwebpdemux2  # 
apt install --only-upgrade libwebp-dev  # 
apt install --only-upgrade libwebpmux3  # 
apt install --only-upgrade libwmf0.2-7  # 
apt install --only-upgrade libwmf-dev  # 
apt install --only-upgrade libx11-6  # 
apt install --only-upgrade libx11-data  # 
apt install --only-upgrade libx11-dev  # 
apt install --only-upgrade libxml2  # 
apt install --only-upgrade libxml2-dev  # 
apt install --only-upgrade libxslt1.1  # 
apt install --only-upgrade libxslt1-dev  # 
apt install --only-upgrade libxtables12  # 
apt install --only-upgrade linux-libc-dev  # 
apt install --only-upgrade login  # 
apt install --only-upgrade m4  # 
apt install --only-upgrade mariadb-common  # 
apt install --only-upgrade minimatch  # 
apt install --only-upgrade mount  # 
apt install --only-upgrade ncurses-base  # 
apt install --only-upgrade ncurses-bin  # 
apt install --only-upgrade nettle-dev  # 
apt install --only-upgrade npm  # 
apt install --only-upgrade @npmcli/arborist  # 
apt install --only-upgrade openssh-client  # 
apt install --only-upgrade openssl  # 
apt install --only-upgrade passwd  # 
apt install --only-upgrade patch  # 
apt install --only-upgrade path-parse  # 
apt install --only-upgrade perl  # 
apt install --only-upgrade perl-base  # 
apt install --only-upgrade perl-modules-5.28  # 
apt install --only-upgrade procps  # 
apt install --only-upgrade python  # 
apt install --only-upgrade python2  # 
apt install --only-upgrade python2.7  # 
apt install --only-upgrade python2.7-minimal  # 
apt install --only-upgrade python2-minimal  # 
apt install --only-upgrade python3.7  # 
apt install --only-upgrade python3.7-minimal  # 
apt install --only-upgrade python-minimal  # 
apt install --only-upgrade qs  # 
apt install --only-upgrade request  # 
apt install --only-upgrade semver  # 
apt install --only-upgrade subversion  # 
apt install --only-upgrade sysvinit-utils  # 
apt install --only-upgrade tar  # 
apt install --only-upgrade tough-cookie  # 
apt install --only-upgrade tzdata  # 
apt install --only-upgrade unzip  # 
apt install --only-upgrade util-linux  # 
apt install --only-upgrade uuid-dev  # 
apt install --only-upgrade wget  # 
apt install --only-upgrade xz-utils  # 
apt install --only-upgrade zlib1g  # 
apt install --only-upgrade zlib1g-dev  # 
Comandos para correção  # 
