apiVersion: v1
kind: Pod
metadata:
  name: portainer-pod
  labels:
    app: portainer-pod
spec:
  containers:
    - name: portainer
      image: portainer/portainer-ce
      ports: 
        - containerPort: 9000
