apiVersion: v1
kind: Service
metadata:
  name: svc-docksec-pod
spec:
  type: ClusterIP
  selector:
    app: docksec-pod
  ports:
    - port: 8080
    nodePort: 8080
  type: NodePort
  externalIPs:
    - 192.168.28.140
