apiVersion: v1
kind: Service
metadata:
  name: svc-docksec-pod
spec:
  type: NodePort
  selector:
    app: docksec-pod
  ports:
    - port: 8080
      targetPort: 8080
  externalIPs:
    - 192.168.28.140
